[package]
name = "embedddingmodel"
version = "0.1.0"
edition = "2021"

[dependencies]
tokenizers = "0.13.4"
ndarray = "0.15.6"
anyhow = "1.0.75"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
fasttext = "0.7.1"
